### ISSUE TITLE
Testing on Chrome

### ISSUE THREAD

**Issue by raineydavid** [womenhackfornonprofits/whfnp#167]
Test the development site: http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/index.html on iPad device (please pm Lili if you need access to browserstack for testing).

- [x] Check that nothing looks broken, things do not overlap anywhere
- [x] Check the layout of all pages looks the same as on Chrome browser, make sure there are no layout issues
- [x] Check you cannot submit forms with missing mandatory/required info
- [x] Try to generate errors when submitting a form, does an appropriate error show?

**Comment by raineydavid** [comment]
Logo missing women hack for non profits description, more apparent on all pages that are not the index as only reference to women hack for non profits is in the footer.
![whfnp-volunteer-logomissingdescription](https://cloud.githubusercontent.com/assets/23113728/20058822/d53feaec-a4ea-11e6-944d-7540d1dc7353.PNG)

On the index page our partners section:
sponsoring spelt incorrectly as sponsiring
![whfnp-index-partners](https://cloud.githubusercontent.com/assets/23113728/20088560/dda376e8-a578-11e6-89d4-045a5e9dc1ef.PNG)

Jaspal's voice is spelt inconsistently eg Jaspals voice and Jaspal's voice and does not mirror the embedded website  image spelling of Jaspal's voice
![whfnp_projects-jaspals](https://cloud.githubusercontent.com/assets/23113728/20058308/336de81a-a4e8-11e6-886e-b02d056fc9c5.PNG)

On the about page, there is a floating line over the text
![whfnp-about](https://cloud.githubusercontent.com/assets/23113728/20057982/6572f834-a4e6-11e6-81be-58b5b9b94720.PNG)

Blog
Publishing directly on medium rather than using canonical links. https://help.medium.com/hc/en-us/articles/217991468-Duplicate-Content-and-SEO

Also public message inconsistent:
Blog mantra:
"Volunteer run community helping women to improve their tech skills while working on real life projects for social good."
![whfnp-blog-mantra](https://cloud.githubusercontent.com/assets/23113728/20058609/bb15cf84-a4e9-11e6-98fc-2b108a0c9fdd.PNG)

Website Mantra:
We are a community of women in tech building open source projects for non-profit organizations and individuals with a cause.
![whfnp-index-mantra](https://cloud.githubusercontent.com/assets/23113728/20058653/f4e82338-a4e9-11e6-8958-756d232cf929.PNG)

Call to Action Buttons
Expecting to volunteers and non-profit buttons on the index hero image.
![whfnp-index-calltoaction](https://cloud.githubusercontent.com/assets/23113728/20059022/ec040fbe-a4eb-11e6-846e-60b5968dc27c.PNG)

Expecting the call to action buttons eg volunteer with us to take me lower down the page to a div with relevant form eg
<a href="#volunteer">Volunteer with us</a>

Contact Us
Expecting to see twitter facebook email etc.. for example:
https://www.britishgas.co.uk/Help_Advice/ContactUs/
whfnp:
![whfnp-contact-missingtwitterfacebook](https://cloud.githubusercontent.com/assets/23113728/20059203/d4b963e4-a4ec-11e6-911f-566ac93117f9.PNG)

Unexpectedly left the site after submitting form to formspree
![whfnp-contact-unexpectedformspree](https://cloud.githubusercontent.com/assets/23113728/20059272/48f23a10-a4ed-11e6-8110-47977b261ecf.PNG)

**Comment by lili2311** [comment]
Thanks!
- Sponsoring spelling fixed in a PR
- We wont be moving away from formspree as it is free, maybe when there is a CMS instead can use that
- no CTAs will be added to homepage, these designs are final.
- no wording will be added under logo these designs are final.
  basically we wont be changing much visually as we agreed to just fixed what we had in tickets up until now. Just looking for bugs at this point to deploy.

**Comment by raineydavid** [comment]
- Please consider moving from formspree to mailchimp, at least you can redirect onto whfnp page http://kb.mailchimp.com/lists/signup-forms/design-and-host-your-own-thank-you-pages
- There is still an issue with speed.. similar for web and mobile
  ![whfnp-website-speedtest](https://cloud.githubusercontent.com/assets/23113728/20060402/ea2b9354-a4f2-11e6-87d7-c403bd7af5d2.PNG)
  ![whfnp-website-speedtest-mobilespeeddetails](https://cloud.githubusercontent.com/assets/23113728/20060406/ec705730-a4f2-11e6-88b7-f678731328aa.PNG)

**Comment by raineydavid** [comment]
Also spam protection for the form eg:
Hidden form fields
https://www.sitepoint.com/easy-spam-prevention-using-hidden-form-fields/

or Recaptcha
https://developers.google.com/recaptcha/

**Comment by raineydavid** [comment]
#Accessibility
##Accessibility Violations
Missing text in <a> links for social icons in footer, no text visible to screen readers
<a class="social-icon medium" href="https://medium.com/women-hack-for-non-profits"></a>

#Images insufficiently described
eg WHFNP logo image rather than Orange W,H,F,N,P letters in capitals for women hack for non profits logo

##colour contrast 
Insufficient on index page - see http://webaim.org/resources/contrastchecker/
For example:
<a href="contact.html" class="button">Become a Partner</a>

Element has insufficient color contrast of 4.41 (foreground color: #ffffff, background color: #e42e3d, font size: 12.0pt, font weight: bold)

Fix any of the following Related Nodes:
body > section:nth-of-type(6) > .container > .col-sm-12 > .button

**Comment by raineydavid** [comment]
#Missing files
Missing venntro image as two g in file name for http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/index.html
https://res.cloudinary.com/drdmdqahj/image/upload/q_auto:good/v1478311036/venntro_logo_mwfngp.pngg 

Missing google analytics file
http://cdn.owlcdn.com/google/analytics/analytics.js

**Comment by lili2311** [comment]
- changes to blog are out of scope
- created tickets to fix colour contrast on buttons
- spam prevention out of scope formspree does this sufficiently and we have received no spam for over a year
- moving away from formspree out of scope

**Comment by raineydavid** [comment]
# Fromspree Redirect

http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/contact.html
 It turns out we can do redirect in Formspree (so no mailchimp required) we can do this by adding _next to another hidden input to specify which url we'd  like users to be sent to one they’ve submitted the form.  Can this be utilised?  Just following tutorial from here: https://webdesign.tutsplus.com/tutorials/quick-tip-add-a-formspree-form-to-your-static-sites--cms-23870

<input type="hidden" name="_next" value="//womenhackfornonprofits.com/thanks.html" /> \

**Comment by lili2311** [comment]
what page are you referring to? if you are mentioning the email signup then we want to use mailchimp

**Comment by raineydavid** [comment]
Updated the comment above to have the correct link .. oops

**Comment by lili2311** [comment]
Redirect added and button colours fixed.
